from setuptools import setup, find_packages

setup(
    name='TOS',
    version='0.0.1',
    packages=find_packages(),
    author='Peili Mao',
    author_email='peili.z.mao@gmail.com',
    description='Transfer Optimiztion System',
    long_description='This is a longer description of my package.',
    url='https://github.com/maopl/TransOpt.git',
    install_requires=[
        "numpy==1.21.6",
        "scipy==1.7.3",
        "pandas==1.3.5",
        "scikit-learn==1.0.2",
        "matplotlib==3.5.1",
        "sobol-seq==0.2.0",
        "gplearn==0.4.2",
        "paramz==0.9.5",
        "emukit==0.4.10",
        "ml-collections==0.1.1",
        "tensorflow",
        "torch",
        "ConfigSpace",
        "seaborn",
        "cliffs-delta==1.0.0",
        # "oslo-concurrency",
        "openpyxl",
        "openml",
        "PyYAML",
        "xgboost",
        "tqdm",
        "torchvision",
        "tikzplotlib",
        "pdf2image",
        "GPy",
        "GPyOpt",
        "tpe",
        "flask",
        "celery",
        "pymoo",
        "gpytorch"
    ],
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
    ],
    keywords='sample package example',
    license='MIT',
)